stages:
 - build

variables:
 STREAM_KEY: jwze-r5ss-tm8d-p0az-a5d3

before_script:
 - apt-get update -y
 - apt-get install -y ffmpeg
 - apt-get install -y nodejs
 - apt-get install -y npm
 - npm install


build:
 stage: build
 script:
   - echo "streamkey=$STREAM_KEY" > .env
   - node main.js
